table factsales_gold
	lineageTag: 2c18b28e-4ff0-4696-a685-75833e2687d0
	sourceLineageTag: [dbo].[factsales_gold]

	measure Sales = SUMX(factsales_gold, factsales_gold[Quantity]*factsales_gold[UnitPrice])
		lineageTag: 18a654c9-d3e4-40a1-9556-7aa2b8feba80

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CustomerID
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: e5a3c353-9f45-4efb-ab46-c4917b090a3f
		sourceLineageTag: CustomerID
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column ItemID
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: f7cf64ab-64fd-47d5-b1b0-c47380309581
		sourceLineageTag: ItemID
		summarizeBy: none
		sourceColumn: ItemID

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: date
		lineageTag: 78bb6a49-855e-4a6f-9d34-eaf3fcc17eb6
		sourceLineageTag: OrderDate
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 2d90ea18-5256-40f7-b992-f2e7f912d88f
		sourceLineageTag: Quantity
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		sourceProviderType: real
		lineageTag: 48bba207-9cf8-4317-8fa3-31d6e183a3f3
		sourceLineageTag: UnitPrice
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Tax
		dataType: double
		sourceProviderType: real
		lineageTag: 7ef253a2-eeb0-4e30-827c-efad384fa217
		sourceLineageTag: Tax
		summarizeBy: sum
		sourceColumn: Tax

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition factsales_gold = entity
		mode: directLake
		source
			entityName: factsales_gold
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

