table Reseller
	lineageTag: c2bc8824-0449-46be-947b-1c0e856226f4

	column ResellerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0cc1c30d-05b8-40ea-9ea4-c76ec73e8092
		summarizeBy: none
		sourceColumn: ResellerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Business Type'
		dataType: string
		lineageTag: 40b0e4e0-843f-4c18-864f-5b53510a8a9e
		summarizeBy: none
		sourceColumn: Business Type

		annotation SummarizationSetBy = Automatic

	column Reseller
		dataType: string
		lineageTag: 9ee0a53f-92ac-424a-8dbb-4127385a61ad
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Reseller

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 86108860-3866-4693-ab26-06f32060c56f
		dataCategory: City
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State-Province
		dataType: string
		lineageTag: af4212cc-cf03-401b-a83c-3231835c30c0
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: State-Province

		annotation SummarizationSetBy = Automatic

	column Country-Region
		dataType: string
		lineageTag: 30a2e130-e1cd-4a06-a563-d6e407cc0dfb
		dataCategory: County
		summarizeBy: none
		sourceColumn: Country-Region

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: a9328d82-4cca-4131-8816-5597a48397b7
		dataCategory: PostalCode
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column 'Reseller ID'
		dataType: string
		lineageTag: cc7015df-999e-48ec-9f25-e08a330bc989
		summarizeBy: none
		sourceColumn: Reseller ID

		annotation SummarizationSetBy = Automatic

	hierarchy Geography
		lineageTag: 2de64f48-e6d7-4d93-a258-d81262c420e2

		level Country-Region
			lineageTag: 9d0eace3-d6c9-4194-a28a-1790f54c99be
			column: Country-Region

		level State-Province
			lineageTag: d621e67d-7185-42e1-b5dc-24352166e171
			column: State-Province

		level City
			lineageTag: 8a060e03-c1fb-4de6-8056-007c41ae3067
			column: City

		level 'Postal Code'
			lineageTag: 1d881c77-8216-47a9-9203-32d18ebd4782
			column: 'Postal Code'

		level Reseller
			lineageTag: e827c914-1e1c-45da-a364-39035c8280be
			column: Reseller

	partition Reseller-e44d0a71-e144-4c32-b1af-2f758a686c3c = m
		mode: import
		source =
				let
				    Source = Sql.Database(SqlServerInstance, SqlServerDatabase),
				    dbo_DimReseller = Source{[Schema="dbo",Item="DimReseller"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_DimReseller,{"ResellerKey", "ResellerAlternateKey", "BusinessType", "ResellerName", "DimGeography"}),
				    #"Expanded DimGeography" = Table.ExpandRecordColumn(#"Removed Other Columns", "DimGeography", {"City", "StateProvinceName", "EnglishCountryRegionName", "PostalCode"}, {"City", "StateProvinceName", "EnglishCountryRegionName", "PostalCode"}),
				    #"Add NA Row" = Table.InsertRows(#"Expanded DimGeography", 0, {[ResellerKey = -1, ResellerAlternateKey = "[Not Applicable]", BusinessType = "[Not Applicable]", ResellerName = "[Not Applicable]", City = "[Not Applicable]", StateProvinceName ="[Not Applicable]", EnglishCountryRegionName ="[Not Applicable]", PostalCode ="[Not Applicable]"]}),
				    #"Renamed Columns" = Table.RenameColumns(#"Add NA Row",{{"ResellerAlternateKey", "Reseller ID"}, {"BusinessType", "Business Type"}, {"ResellerName", "Reseller"}, {"StateProvinceName", "State-Province"}, {"EnglishCountryRegionName", "Country-Region"}, {"PostalCode", "Postal Code"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

