table 'Sales Order'
	lineageTag: fadb978c-49d2-4c2a-862c-ed2200d6abb6

	column SalesOrderLineKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b7b17fef-3b06-416b-8ecb-e59caff01447
		summarizeBy: none
		sourceColumn: SalesOrderLineKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sales Order'
		dataType: string
		lineageTag: 9b96a7b3-6732-438e-bf19-fc25506f0d1e
		summarizeBy: none
		sourceColumn: Sales Order

		annotation SummarizationSetBy = Automatic

	column 'Sales Order Line'
		dataType: string
		lineageTag: 2ab7f9e5-cdba-4626-b74d-935ac4996d6b
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Sales Order Line
		sortByColumn: SalesOrderLineKey

		annotation SummarizationSetBy = Automatic

	column Channel
		dataType: string
		lineageTag: c9e7c64c-fa37-41d0-b5d8-43e65c1bc510
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	hierarchy 'Sales Orders'
		lineageTag: 60788123-58da-4015-980e-a6526a86fb78

		level 'Sales Order'
			lineageTag: 327f81d0-4217-427b-b556-fc12f5658d50
			column: 'Sales Order'

		level 'Sales Order Line'
			lineageTag: 10d3a02f-b5f0-4365-bc68-424a15baa534
			column: 'Sales Order Line'

	partition 'Sales Order-3ce1b467-3e1b-4732-b605-3e94fee75991' = m
		mode: import
		source =
				let
				    Source = Sql.Database(SqlServerInstance, SqlServerDatabase),
				    dbo_vFactSales = Source{[Schema="dbo",Item="vFactSales"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_vFactSales,{"Channel", "SalesOrderLineKey", "SalesOrderNumber", "SalesOrderLineNumber"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"SalesOrderNumber", "Sales Order"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Sales Order Line", each [Sales Order] & " - " & Text.PadStart(Number.ToText([SalesOrderLineNumber]), 2, "0")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Sales Order Line", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"SalesOrderLineNumber"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

