// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table MyStockData (['time']:datetime, symbol:string, sector:string, securityType:string, bidPrice:string, bidSize:string, askPrice:string, askSize:string, lastUpdated:string, lastSalePrice:string, lastSaleSize:string, lastSaleTime:string, volume:string, marketPercent:string, seq:string, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
