// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table DES_tbl_20240605 (COUNT_BikepointID:dynamic, Window_End_Time:datetime) 
.create-merge table AllDataEventStream (BikepointID:string, Street:string, Neighbourhood:string, Latitude:dynamic, Longitude:dynamic, No_Bikes:long, No_Empty_Docks:long, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
